"""make is clustering field on board model


Revision ID: 817db9b2306f
Revises: b425affd4d43
Create Date: 2025-11-07 16:50:42.597474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817db9b2306f'
down_revision: Union[str, Sequence[str], None] = 'b425affd4d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('is_clustering', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'is_clustering')
    # ### end Alembic commands ###
