"""add cluster_labels table

Revision ID: 960be8892776
Revises: aa72e9e60809
Create Date: 2025-10-30 16:12:17.185036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960be8892776'
down_revision: Union[str, Sequence[str], None] = 'aa72e9e60809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_index(op.f('ix_cluster_labels_id'), 'cluster_labels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_labels_id'), table_name='cluster_labels')
    op.drop_table('cluster_labels')
    # ### end Alembic commands ###
