"""add board id to cluster label

Revision ID: b425affd4d43
Revises: ece56c27ecda
Create Date: 2025-11-07 15:51:38.555672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b425affd4d43'
down_revision: Union[str, Sequence[str], None] = 'ece56c27ecda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_labels', sa.Column('board_id', sa.Integer(), nullable=False))
    op.alter_column('cluster_labels', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cluster_labels', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('cluster_labels_cluster_id_key'), 'cluster_labels', type_='unique')
    op.create_unique_constraint('uq_board_cluster', 'cluster_labels', ['board_id', 'cluster_id'])
    op.create_foreign_key(None, 'cluster_labels', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cluster_labels', type_='foreignkey')
    op.drop_constraint('uq_board_cluster', 'cluster_labels', type_='unique')
    op.create_unique_constraint(op.f('cluster_labels_cluster_id_key'), 'cluster_labels', ['cluster_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('cluster_labels', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cluster_labels', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('cluster_labels', 'board_id')
    # ### end Alembic commands ###
