"""remove cluster label board id

Revision ID: da6d977cb1e3
Revises: 4d2eb81f8bb8
Create Date: 2025-11-01 17:19:10.171079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6d977cb1e3'
down_revision: Union[str, Sequence[str], None] = '4d2eb81f8bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cluster_labels_board_id_boards'), 'cluster_labels', type_='foreignkey')
    op.drop_column('cluster_labels', 'board_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_labels', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_cluster_labels_board_id_boards'), 'cluster_labels', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###
