"""integrate board id to clusterlabel

Revision ID: f1e1aa2cddf4
Revises: 2713169914a2
Create Date: 2025-11-01 16:59:34.366736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e1aa2cddf4'
down_revision: Union[str, Sequence[str], None] = '2713169914a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
